language: python
python:
    - 2.7
    - 3.2
    - 3.3
install: pip install pytest-cov coveralls
script:
    - python setup.py build
    - cd build/lib*
    - py.test -v --cov snakeoil
after_success: coveralls
