language: python
python:
    - 2.7
    - 3.3
    - 3.4
sudo: false
install: pip install 'tox<2' coveralls
script: tox -e py
after_success:
    # convert pylint plugins as necessary for py3k
    - if [[ ${TRAVIS_PYTHON_VERSION} == 3* ]]; then 2to3 -wn lintplugin/*.py; fi

    - pushd .tox/py/lib/python${TRAVIS_PYTHON_VERSION}/site-packages
    # upload coverage data to coveralls.io
    - coveralls
    # run pylint checks
    #- ${TRAVIS_BUILD_DIR}/pylint -f colorized --reports y snakeoil
    - popd
