# config linter: https://lint.travis-ci.org/

language: python
python:
    - 2.7
    - 3.3
    - 3.4
install: pip install tox coveralls pylint
script: tox -e py
after_success:
    # upload coverage data to coveralls.io
    - pushd .tox/py/lib/python${TRAVIS_PYTHON_VERSION}/site-packages
    - coveralls
    - popd

    # run pylint checks
    - if [[ ${TRAVIS_PYTHON_VERSION} == 3* ]]; then 2to3 -wn lintplugin/*.py; fi
    - ./pylint -f colorized --reports y build/lib*/snakeoil
